import React from "react";

import jsPDF from "jspdf";

import autoTable from "jspdf-autotable";

import { saveAs } from "file-saver";

function ExportReport({
  transactions
}) {

  // PDF EXPORT
  const exportPDF = () => {

    const doc = new jsPDF();

    // TOTALS
    const totalIncome =
      transactions
        .filter(
          (item) =>
            item.type === "Income"
        )
        .reduce(
          (total, item) =>
            total + Number(item.amount),
          0
        );

    const totalExpense =
      transactions
        .filter(
          (item) =>
            item.type === "Expense"
        )
        .reduce(
          (total, item) =>
            total + Number(item.amount),
          0
        );

    const balance =
      totalIncome - totalExpense;

    // TITLE
    doc.setFontSize(24);

    doc.text(
      "AI Personal Finance Report",
      14,
      20
    );

    // DATE
    doc.setFontSize(12);

    doc.text(
      `Generated On: ${new Date().toLocaleString()}`,
      14,
      30
    );

    // SUMMARY
    doc.setFontSize(16);

    doc.text(
      `Total Income: Rs. ${totalIncome}`,
      14,
      45
    );

    doc.text(
      `Total Expense: Rs. ${totalExpense}`,
      14,
      55
    );

    doc.text(
      `Balance: Rs. ${balance}`,
      14,
      65
    );

    // TABLE
    autoTable(doc, {

      startY: 80,

      head: [[
        "Category",
        "Merchant",
        "Type",
        "Amount",
        "Date",
      ]],

      body: transactions.map(
        (transaction) => [

          transaction.category,

          transaction.merchant,

          transaction.type,

          `Rs. ${transaction.amount}`,

          transaction.date,

        ]
      ),

    });

    // FOOTER
    doc.setFontSize(10);

    doc.text(
      "Generated by AI Personal Finance Coach",
      14,
      doc.internal.pageSize.height - 10
    );

    // SAVE
    doc.save(
      "AI-Finance-Report.pdf"
    );

  };

  // CSV EXPORT
  const exportCSV = () => {

    const headers = [
      "Category",
      "Merchant",
      "Type",
      "Amount",
      "Date"
    ];

    const rows =
      transactions.map(
        (transaction) => [

          transaction.category,

          transaction.merchant,

          transaction.type,

          transaction.amount,

          transaction.date,

        ].join(",")
      );

    const csvContent =

      [
        headers.join(","),

        ...rows

      ].join("\n");

    const blob = new Blob(
      [csvContent],
      {
        type:
          "text/csv;charset=utf-8;",
      }
    );

    saveAs(
      blob,
      "AI-Finance-Report.csv"
    );

  };

  return (

    <div className="flex flex-col md:flex-row gap-4">

      {/* PDF BUTTON */}
      <button
        onClick={exportPDF}
        className="bg-green-600 hover:bg-green-700 text-white px-6 py-3 rounded-2xl font-semibold transition"
      >

        Download PDF

      </button>

      {/* CSV BUTTON */}
      <button
        onClick={exportCSV}
        className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-2xl font-semibold transition"
      >

        Download CSV

      </button>

    </div>

  );

}

export default ExportReport;