# Generated by Django 3.2 on 2026-05-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=100),
            preserve_default=False,
        ),
    ]
