from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

from reportlab.platypus.flowables import PageBreak

from .models import Transaction


def generate_finance_report(file_path):

    doc = SimpleDocTemplate(file_path)

    styles = getSampleStyleSheet()

    elements = []

    # TITLE
    title = Paragraph(
        "AI Personal Finance Report",
        styles['Title']
    )

    elements.append(title)

    elements.append(Spacer(1, 20))

    # TABLE DATA
    data = [[
        "User",
        "Merchant",
        "Amount",
        "Category",
        "Date"
    ]]

    transactions = Transaction.objects.all()

    total_spending = 0

    for transaction in transactions:

        data.append([

            transaction.user.name,
            transaction.merchant,
            str(transaction.amount),
            transaction.category,
            str(transaction.date)

        ])

        total_spending += transaction.amount

    # TABLE
    table = Table(data)

    table.setStyle(TableStyle([

        ('BACKGROUND', (0, 0), (-1, 0), colors.blue),

        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),

        ('GRID', (0, 0), (-1, -1), 1, colors.black),

        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),

        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),

    ]))

    elements.append(table)

    elements.append(Spacer(1, 30))

    # TOTAL SPENDING
    total_text = Paragraph(

        f"<b>Total Spending:</b> ₹{total_spending}",

        styles['Heading2']

    )

    elements.append(total_text)

    elements.append(PageBreak())

    # FINAL MESSAGE
    footer = Paragraph(

        "Generated by AI Personal Finance Coach",

        styles['Normal']

    )

    elements.append(footer)

    # BUILD PDF
    doc.build(elements)